In [1]:
from evaluate import *
from svd import *
from bert import *
from document import *
from sklearn.metrics.pairwise import cosine_similarity
from scipy.spatial.distance import jensenshannon
%load_ext autoreload
%autoreload 2

In [2]:
cosfname = "assets/cos_full"

In [3]:
l = SvdBaseline(cosfname)
l.load("assets/log_100")

/home/selo/anaconda3/envs/ml-agents/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.decomposition.online_lda module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/selo/anaconda3/envs/ml-agents/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LatentDirichletAllocation from version 0.21.3 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [4]:
lda = l.lda
lda_mat = l.doc_mat
tf_idf = l.tf_idf

In [6]:
import numpy as np
from sklearn import decomposition
from scipy import linalg
import matplotlib.pyplot as plt
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import NMF

In [10]:
svd = TruncatedSVD(n_components=100, random_state=0)

In [12]:
svd.fit(tf_idf)

TruncatedSVD(algorithm='randomized', n_components=100, n_iter=5, random_state=0,
             tol=0.0)

In [13]:
from joblib import dump, load

In [15]:
dump(svd, "assets/svd100")

['assets/svd100']

In [84]:
%time U, s, Vh = scipy.linalg.svd(l.tf_idf.todense(), full_matrices=False)

ValueError: Sparse matrices are not supported by this function. Perhaps one of the scipy.sparse.linalg functions would work instead.

In [60]:
lda_mat.shape

(191113, 100)

In [61]:
lda.components_.shape

(100, 135145)

In [62]:
v1 = l.tf_idf[0,:]

In [65]:
v1t = lda._unnormalized_transform(v1)

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   1 out of   1 | elapsed:    0.0s finished


In [66]:
v1t.shape

(1, 100)

In [69]:
sim = cosine_similarity(lda_mat, v1t)[:, 0]

In [68]:
#sim.sort()

In [70]:
sim[:100]

array([1.        , 0.01567552, 0.00449813, 0.00645159, 0.20851149,
       0.00509312, 0.00559347, 0.00748178, 0.00613798, 0.00675197,
       0.00686474, 0.00507146, 0.00760364, 0.01838678, 0.00793569,
       0.3186383 , 0.32265943, 0.0057386 , 0.00560834, 0.00585418,
       0.00504656, 0.00509668, 0.01886648, 0.00685777, 0.0057807 ,
       0.00966281, 0.0044818 , 0.00721908, 0.00855931, 0.00461534,
       0.00566772, 0.00412278, 0.00561873, 0.00864036, 0.00551905,
       0.0046067 , 0.00518043, 0.00879181, 0.00657389, 0.00626442,
       0.00644452, 0.00626587, 0.9361829 , 0.00691375, 0.00678517,
       0.00517388, 0.00490478, 0.0051894 , 0.00565587, 0.00514543,
       0.00745998, 0.13952685, 0.01305496, 0.01186419, 0.01445774,
       0.01445774, 0.0174241 , 0.01445774, 0.00656696, 0.00661439,
       0.0044571 , 0.00625639, 0.9280075 , 0.56570409, 0.00759364,
       0.00567971, 0.00802887, 0.00611708, 0.00676262, 0.00594707,
       0.00611329, 0.00530819, 0.00601807, 0.00539888, 0.00576

In [79]:
(-sim).argsort()[:100]

array([     0, 165772,  83867,  13785, 185476, 139989,   8937,  80218,
        62228,    691,  41436,   4674,  36491, 170305, 140145,  19765,
        58721, 162867, 178857, 138433, 139324, 135893,  67509, 124395,
        13338, 181905, 149203, 158465,  45176, 190970,   3071,  81281,
        55112,  69092, 143563, 137821, 150342,  86073, 159954, 136052,
       158765, 154880,  14421,  13335,  83580,  12460, 169954, 180335,
         1799, 187891, 157754,   1840, 146264, 148019, 147213,  78903,
         2992, 154391,  79634, 177700,  26512, 157687,  49091,   4454,
       153495, 150646, 147624, 132834, 165057, 159642, 172801, 181897,
       142627, 143330,  87587, 149550, 144186, 132582,   2166, 189162,
         6478, 153672, 154560, 148319, 155518, 171902, 157146,  12031,
       133193,   2134,  87551,  84290, 149648,   1117,  16097, 154108,
       184913, 187279,   6867, 183885])

In [77]:
lda_mat[0, :]

array([0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 4.8983968 , 0.01      , 0.01      , 0.01      ,
       0.01      , 1.72322241, 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01   

In [73]:
v1t

array([[0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 4.8983968 , 0.01      , 0.01      , 0.01      ,
        0.01      , 1.72322241, 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
        0.01      , 0.01      , 0.01      , 0.01

In [80]:
cosine_similarity(v1t, lda_mat[165772, :].reshape(1, -1))

array([[0.99200399]])

In [ ]:
#unnormalized_transform

In [6]:
topics = load_topics(retrieve="even")

In [8]:
id2word = {a:b for b, a in l.word2id.items()}
for i, topic in enumerate(l.lda.components_):
    print("Topic {}:".format(i))
    print([id2word[i] for i in topic.argsort()[-10:]])
    print("-"*50)

Topic 0:
['resect', 'techniqu', 'complic', 'surgic', 'oper', 'postop', 'group', 'patient', 'surgeri', 'laparoscop']
--------------------------------------------------
Topic 1:
['alert', 'silenc', 'overdos', 'covid', 'compassion', 'abus', 'remdesivir', 'sirna', 'rnai', 'opioid']
--------------------------------------------------
Topic 2:
['commun', 'polici', 'diseas', 'social', 'research', 'global', 'covid', 'pandem', 'public', 'health']
--------------------------------------------------
Topic 3:
['cessat', 'vape', 'nicotin', 'tracheotomi', 'covid', 'tobacco', 'cigarett', 'smoker', 'thyroid', 'smoke']
--------------------------------------------------
Topic 4:
['hypertens', 'enzym', 'blocker', 'acei', 'convert', 'ace', 'renin', 'inhibitor', 'arb', 'angiotensin']
--------------------------------------------------
Topic 5:
['altitud', 'superspread', 'regard', 'repli', 'respons', 'covid', 'al', 'et', 'editor', 'letter']
--------------------------------------------------
Topic 6:
['recommen

['covid', 'nucleolu', 'diseas', 'surveil', 'line', 'erythematosu', 'infecti', 'lupu', 'front', 'updat']
--------------------------------------------------
Topic 69:
['inflammatori', 'mesenchym', 'multisystem', 'exosom', 'teledermatolog', 'geriatr', 'covid', 'orthopaed', 'msc', 'kawasaki']
--------------------------------------------------
Topic 70:
['covid', 'target', 'proteas', 'activ', 'inhibitor', 'compound', 'antivir', 'cov', 'sar', 'drug']
--------------------------------------------------
Topic 71:
['northern', 'india', 'prepared', 'pandem', 'africa', 'hiv', 'learn', 'itali', 'covid', 'lesson']
--------------------------------------------------
Topic 72:
['bovin', 'viru', 'de', 'porcin', 'pig', 'felin', 'calv', 'pedv', 'diarrhea', 'cat']
--------------------------------------------------
Topic 73:
['second', 'link', 'correct', 'top', 'manifest', 'melatonin', 'amend', 'publish', 'paper', 'cutan']
--------------------------------------------------
Topic 74:
['varicella', 'simplex',

In [112]:
evals = eval_topics(topics, l)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


(100, 191113) (100, 191113) (100, 191113)
0 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


1 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


2 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


3 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


4 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


5 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


6 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


7 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


8 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


9 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


10 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


11 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


12 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


13 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


14 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


15 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


16 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


17 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


18 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


19 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


20 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


21 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


22 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


23 / 25
(100, 191113) (100, 191113) (100, 191113)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


24 / 25


/home/selo/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,4,5,6,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


AttributeError: 'super' object has no attribute 'load'